# Generated by Django 3.1.2 on 2020-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='grade'),
        ),
    ]
