# Generated by Django 3.1.2 on 2020-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201025_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='followers_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='following_number'),
        ),
    ]
